# creation of the hsg gene lists

In [ ]:
import scanpy as sc
import pandas as pd
import numpy as np

#### upload first big gene list from
https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-019-2886-2

In [ ]:
hsg_big=pd.read_csv("/scratch200/reutj/data/hsg_gene_lists/hsg_big.csv")

In [34]:
hsg_big

,Gene Name,Ensembl ID,Chromosome,Gene Type,General Gene Type,Mechanism of Origin,General Mechanism of Origin,Reference(s)
0,39326,ENSG00000122545,7,protein_coding,protein-coding,human-specific gene duplication,gene amplification,9
1,AATBC,ENSG00000215458,21,antisense,long non-coding,hominoid-specific de novo originated protein-c...,de novo origin,1
2,ABCB10,ENSG00000135776,1,protein_coding,protein-coding,human-specific gene amplification,gene amplification,"2,3"
3,ABCC12,ENSG00000140798,16,protein_coding,protein-coding,modern human-specific coding change,gene sequence alteration,4
4,ABCC6,ENSG00000091262,16,protein_coding,protein-coding,human-specific gene duplication or expansion,gene amplification,5
...,...,...,...,...,...,...,...,...
868,ZNF790,ENSG00000197863,19,protein_coding,protein-coding,human-specific gene duplication,gene amplification,22
869,ZNF843,ENSG00000176723,16,protein_coding,protein-coding,human-specific de novo originated protein-codi...,de novo origin,8
870,ZNF85,ENSG00000105750,19,protein_coding,protein-coding,human-specific gene,human-specific gene (undefined feature),29
871,ZNF850,ENSG00000267041,19,protein_coding,protein-coding,human-specific gene loss or pseudogene,gene loss,36
872,ZNF962P,ENSG00000215604,13,unprocessed_pseudogene,pseudogene,human-specific gene,human-specific gene (undefined feature),6

## what do we want to filter:
* The goal here is to remain only with relevant protein coding genes (or at least mostly)
* So first we will get rid of pseudogenes and har
* Also to get rid of lost in shimapnze or lost gene- cause its not a gain of function
* also remove all undefined feature since we cant say what is the process that have created them or makes them human specific genes

In [40]:
hsg_big_filt=hsg_big[~(hsg_big["General Gene Type"]=="pseudogene")]
hsg_big_filt=hsg_big_filt[~(hsg_big_filt["General Mechanism of Origin"].isin(['lost in chimpanzee','human accelerated region','gene loss','human-specific gene (undefined feature)']))]
hsg_big_filt=hsg_big_filt[~(hsg_big_filt["Mechanism of Origin"]=='flanking human accelerated region')]
hsg_big_filt

,Gene Name,Ensembl ID,Chromosome,Gene Type,General Gene Type,Mechanism of Origin,General Mechanism of Origin,Reference(s)
0,39326,ENSG00000122545,7,protein_coding,protein-coding,human-specific gene duplication,gene amplification,9
1,AATBC,ENSG00000215458,21,antisense,long non-coding,hominoid-specific de novo originated protein-c...,de novo origin,1
2,ABCB10,ENSG00000135776,1,protein_coding,protein-coding,human-specific gene amplification,gene amplification,"2,3"
3,ABCC12,ENSG00000140798,16,protein_coding,protein-coding,modern human-specific coding change,gene sequence alteration,4
4,ABCC6,ENSG00000091262,16,protein_coding,protein-coding,human-specific gene duplication or expansion,gene amplification,5
...,...,...,...,...,...,...,...,...
864,ZNF595,ENSG00000272602,4,protein_coding,protein-coding,human-specific gene duplication or copy number...,gene amplification,"9,5,23"
865,ZNF638,ENSG00000075292,2,protein_coding,protein-coding,splice site mutation fixed in modern humans,gene structure alteration,4
867,ZNF705G,ENSG00000215372,8,protein_coding,protein-coding,human-specific gene duplication,gene amplification,7
868,ZNF790,ENSG00000197863,19,protein_coding,protein-coding,human-specific gene duplication,gene amplification,22
869,ZNF843,ENSG00000176723,16,protein_coding,protein-coding,human-specific de novo originated protein-codi...,de novo origin,8

In [41]:
#change first gene name to convention-SEPTIN7:
hsg_big_filt.iloc[0,0]='SEPTIN7'

## de-novo-genes:
here i will upload data from 2023 nature paper examining de-novo - https://pubmed.ncbi.nlm.nih.gov/36928843/.
almost all are lncRNA with some annotated in gene cards as pseudogenes but shown in the paper to be transcribed

In [42]:
de_novo=pd.read_csv("/scratch200/reutj/data/hsg_gene_lists/de_novo_genes.csv",encoding='cp1252')

In [66]:
de_novo

,Gene stable ID,Gene name,Annotated as,De novo status determined,Associated with disease,#Method of conservation detection,$Detection of Translation,Number of exons,Protein length,Overlap with other genes,...,Start coords,End coords,CDS overlap with current gene structure,Expressed in tissue (highest),Relative Expression level,*Annotated ortholog in,Evolutionary age,Mode of evolution,Enabling mutation,Coding sequence
0,ENSG00000008517,IL32,protein_coding,42,"Inflammation 64, various cancers 65,66, IBD 67...","A,B&C",M 69,7,188,No,...,3065812;3067377;3067554;3067984;3068180;3068990,3065826;3067415;3067613;3068010;3068239;3069355,overlap,Lymphocytes,Medium,"H, B, C, Go",Simiiformes,likely de_novo in primates,out-of-frame insertion extended the frame,MCFPKVLSDDMKKLKARMHQAIERFYDKMQNAESGRGQVMSSLAEL...
1,ENSG00000145063,AC062028.1,lncRNA,"42,44",-,"A,B&C",M 69,7,174,No,...,11105618;11120763;11124583;11128721,11105662;11120962;11124785;11128797,overlap,Brain,Medium,H,Hominoid,de_novo in primates,out-of-frame deletion extended the frame,MGLLSQRKWTLSGSQQTGCVALTVPSFPWVASRMHYGRKQVSWIIF...
2,ENSG00000149443,SCP2D1-AS1,lncRNA,"42,70",-,"A,B&C","R 71, M 69",3,151,Opposite strand overlap,...,18809776;18825266;18830019,18810115;18825348;18830051,overlap,-,Low,H,Primates,de_novo in mammals,lost stop codon extended the frame,MFQVFKPHAGEDYKYPRETETIWSHPYVVEGSHKSPLESLSLHGCL...
3,ENSG00000149656,LINC00266-1/RBRP spetin14/septin14p20,lncRNA,18,"Various cancers 18,72","A,B&C",WB 18,1,71,No,...,64294918;64303151,64295059;64303224,overlap,Brain,Low,H,Hominoid,partial genomic rearrangement,unclear,MIQQEEIRKLEEEKKQLEGEIIDFYKMKAASEALQTQLSTDTKKDK...
4,ENSG00000167747,C19orf48,transcribed_unitary_pseudogene,"42,44",Renal cell carcinoma 73,"A,B&C","R 40, M 69",5,117,No,...,50798095,50798448,overlap,Prostate/Lymphocytes,Medium,"H, C & O",Catarrhini,de_novo in primates,lost stop codon extended the frame,MTVLEAVLEIQAITGSRLLSMVPGPARPPGSCWDPTQCTRTWLLSH...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,ENSG00000267452,LINC02073,lncRNA,43,-,B&C,M 69,5,175,Opposite strand overlap,...,51337118,51337645,overlap,-,NaN,H,Human,de_novo in primates,out-of-frame insertion extended the frame,MPQWLVASIIPGCVCESVSRGDSHVSQRAEKETRSQCECALSNQLK...
78,ENSG00000267535,LINC00868,lncRNA,43,-,B&C,M 43,2,150,No,...,76850366;76861476,76850673;76861620,overlap,Testis,Low,H,Human,de_novo in primates,lost stop codon extended the frame,MTFFSTMRKWYFCVLQISQAGLSGNQGGAFWKRMMLSIRVPGQPAA...
79,ENSG00000273409,LINC02712,lncRNA,46,-,"A,B&C",R 46,3,58,No,...,127311895,127312071,partial,Brain,Low,H,Simiiformes,de_novo in primates,"out-of-frame insertion extended the frame, acq...",MPPTVTSWPLILFHYSHRYLMVLYWWPSMNRYFVPRRNGAILYVIQ...
80,ENSG00000279261,AL360294.1/PP2672 LINC02961,lncRNA,43,-,B&C,M 69,1,182,No,...,234759304,234759852,overlap,-,NaN,"H, C & Go",Hominoid,de_novo in primates,out-of-frame deletion extended the frame,MKSSEELQCLKQMEEELLFLKAGQGSQRARLTPPLPRALQGNFGAP...
81,ENSG00000281832,LINC00602,lncRNA,43,-,B&C,"M 69,83",1,234,Opposite strand overlap,...,165988126,165988830,overlap,Pituitary gland,Low,"H, C & Go",Simiiformes,de_novo in primates,unclear,MTSVASLPEQSPGYRCRSLTGAGARTSAAGPLARLLPRRRLPPPHL...

* after carefull examination of gene names - especially in those with 2 names in the list. i have found the more suitable gene name for some genes here. still there are some transcripts with no canonical gene name (just ensg) and with transcript id duch as 'AC062028.1	' those will b left as they are and will be probably filtered any way when looking which of them are represented in the data

In [43]:
#--genes names that i changes or chose only one name:

#ENSG00000149656- LINC00266-1 (the real name is spetin14/septin14p20 but couldnt decide between them)
#ENSG00000176236- RPP38-DT
#ENSG00000176912- TYMSOS
#ENSG00000176984- LOC107984399
#ENSG00000179253- LOC100128310
#ENSG00000196273- LINC00523
#ENSG00000198547- C20orf203
#ENSG00000204666- ZNF473CR
#ENSG00000205424- PCBP3-AS1
#ENSG00000213904- LIPE-AS1
#ENSG00000228624- HDAC2-AS2
#ENSG00000231811- LOC101927888
#ENSG00000233718- MYCNOS
#ENSG00000237372- CDC42EP3-AS1
#ENSG00000243004- MACC1
#ENSG00000250091- DNAH10OS 
#ENSG00000261175- LINC02188
#ENSG00000279261- LINC02961


de_novo.loc[de_novo["Gene stable ID"]=='ENSG00000149656','Gene name']='LINC00266-1'
de_novo.loc[de_novo["Gene stable ID"]=='ENSG00000176236','Gene name']='RPP38-DT'
de_novo.loc[de_novo["Gene stable ID"]=='ENSG00000176912','Gene name']='TYMSOS'
de_novo.loc[de_novo["Gene stable ID"]=='ENSG00000176984','Gene name']='LOC107984399'
de_novo.loc[de_novo["Gene stable ID"]=='ENSG00000179253','Gene name']='LOC100128310'
de_novo.loc[de_novo["Gene stable ID"]=='ENSG00000196273','Gene name']='LINC00523'
de_novo.loc[de_novo["Gene stable ID"]=='ENSG00000198547','Gene name']='C20orf203'
de_novo.loc[de_novo["Gene stable ID"]=='ENSG00000204666','Gene name']='ZNF473CR'
de_novo.loc[de_novo["Gene stable ID"]=='ENSG00000205424','Gene name']='PCBP3-AS1'
de_novo.loc[de_novo["Gene stable ID"]=='ENSG00000213904','Gene name']='LIPE-AS1'
de_novo.loc[de_novo["Gene stable ID"]=='ENSG00000228624','Gene name']='HDAC2-AS2'
de_novo.loc[de_novo["Gene stable ID"]=='ENSG00000231811','Gene name']='LOC101927888'
de_novo.loc[de_novo["Gene stable ID"]=='ENSG00000233718','Gene name']='MYCNOS'
de_novo.loc[de_novo["Gene stable ID"]=='ENSG00000237372','Gene name']='CDC42EP3-AS1'
de_novo.loc[de_novo["Gene stable ID"]=='ENSG00000243004','Gene name']='MACC1'
de_novo.loc[de_novo["Gene stable ID"]=='ENSG00000250091','Gene name']='DNAH10OS'
de_novo.loc[de_novo["Gene stable ID"]=='ENSG00000261175','Gene name']='LINC02188'
de_novo.loc[de_novo["Gene stable ID"]=='ENSG00000279261','Gene name']='LINC02961'

In [44]:
# add the de-novo genes that do not appear in the hsg to hsg 
de_novo_filt=de_novo[~de_novo["Gene stable ID"].isin(hsg_big_filt["Ensembl ID"].tolist())]

In [45]:
#in order to add we will chnage both column names in the tables
de_novo_filt=de_novo_filt.rename(columns={'Gene stable ID':'ens','Gene name':'gene'})

hsg_big_filt=hsg_big_filt.rename(columns={'Ensembl ID':'ens','Gene Name':'gene','Gene Type':'Annotated as'})
hsg_new=pd.concat([hsg_big_filt.iloc[:,[0,1,3]],de_novo_filt.iloc[:,[1,0,2]]],ignore_index=True)
hsg_new

          gene              ens    Annotated as
0      SEPTIN7  ENSG00000122545  protein_coding
1        AATBC  ENSG00000215458       antisense
2       ABCB10  ENSG00000135776  protein_coding
3       ABCC12  ENSG00000140798  protein_coding
4        ABCC6  ENSG00000091262  protein_coding
..         ...              ...             ...
584  LINC02073  ENSG00000267452          lncRNA
585  LINC00868  ENSG00000267535          lncRNA
586  LINC02712  ENSG00000273409          lncRNA
587  LINC02961  ENSG00000279261          lncRNA
588  LINC00602  ENSG00000281832          lncRNA

[589 rows x 3 columns]

* de-novo genes that were filtered out

In [46]:
de_novo_out=pd.read_csv("/scratch200/reutj/data/hsg_gene_lists/de_novo_filt_out.csv")
de_novo_out

,Reason for exclusion,Old gene ID (for current Ensembl gene Ids) or new gene ID (for non-supported Ensembl gene Ids),Gene stable ID,Gene name,De novo status determined,Annotated as,Method of conservation detection
0,Main ORF not de novo,NaN,ENSG00000026950,BTN3A1,89,protein_coding,B&C
1,Merged/new ID in list,ENSG00000257267!,ENSG00000118267,NaN,"42, 44",NaN,NaN
2,Found not to be de novo by orthologues,ENSG00000215848,ENSG00000125462!,C1orf61,"42, 44",protein_coding,"A,B&C"
3,Main ORF not de novo,NaN,ENSG00000134369,NAV1,89,protein_coding,B&C
4,Not supported in current Ensembl version,NaN,ENSG00000136242,NaN,"42, 43",NaN,B&C
...,...,...,...,...,...,...,...
102,Not supported in current Ensembl version,NaN,ENSG00000256842,AP001468.2,45,NaN,B&C
103,Not supported in current Ensembl version,NaN,ENSG00000257100,NaN,45,NaN,B&C
104,Failed to meet de novo criteria in re-analysis,NaN,ENSG00000257267,ZNF271P,"42, 46",transcribed_unitary_pseudogene,"A,B&C"
105,Not supported in current Ensembl version,NaN,ENSG00000258961,RP11-326A13.2,45,NaN,B&C
106,Failed to meet de novo criteria in re-analysis,NaN,ENSG00000265096,C1QTNF1-AS1,43,lncRNA,"A,B&C"

In [47]:
#check if filtered out genes appear here
sum(de_novo_out["Gene stable ID"].isin(hsg_new.ens.tolist()))

4

In [48]:
#there are 4. lets remove them
hsg_new=hsg_new[~(hsg_new.ens.isin(de_novo_out["Gene stable ID"].tolist()))]

In [49]:
hsg_new.iloc[:10,:]

         gene              ens    Annotated as
0     SEPTIN7  ENSG00000122545  protein_coding
1       AATBC  ENSG00000215458       antisense
2      ABCB10  ENSG00000135776  protein_coding
3      ABCC12  ENSG00000140798  protein_coding
4       ABCC6  ENSG00000091262  protein_coding
5       ABCD4  ENSG00000119688  protein_coding
6     ABHD17A  ENSG00000129968  protein_coding
7  AC005042.4  ENSG00000204380       antisense
8  AC062028.1  ENSG00000145063         lincRNA
9  AC096670.3  ENSG00000204581       antisense

### change weird naming hsg genes:
- here i want to go through all new_hsg gene names and see if in those annotated as lncrna/antisense
  we get weird names and if they are not matching gene cards we will replace

In [50]:
hsg_new[hsg_new["Annotated as"].isin(["antisense","lincRNA"])]

              gene              ens Annotated as
1            AATBC  ENSG00000215458    antisense
7       AC005042.4  ENSG00000204380    antisense
8       AC062028.1  ENSG00000145063      lincRNA
9       AC096670.3  ENSG00000204581    antisense
12     ADORA2A-AS1  ENSG00000178803    antisense
17      AL592528.1  ENSG00000205424    antisense
45        C1orf229  ENSG00000221953      lincRNA
47       C20orf203  ENSG00000198547      lincRNA
48    C21orf62-AS1  ENSG00000205930      lincRNA
49        C2orf27B  ENSG00000186825      lincRNA
88         CROCCP2  ENSG00000215908      lincRNA
92     CTA-373H7.7  ENSG00000206028      lincRNA
132         FAM27L  ENSG00000178130      lincRNA
137        FAM95B1  ENSG00000223839      lincRNA
148       FLJ35934  ENSG00000220161      lincRNA
212       KIAA0125  ENSG00000226777      lincRNA
226      LINC00152  ENSG00000222041      lincRNA
227      LINC00240  ENSG00000224843      lincRNA
228      LINC00314  ENSG00000178457      lincRNA
230      LINC00523  ENSG00000196273      lincRNA
231      LINC00632  ENSG00000203930      lincRNA
233      LINC01102  ENSG00000235597      lincRNA
274     MRGPRG-AS1  ENSG00000236301    antisense
279         MYCNOS  ENSG00000233718    antisense
409  RP11-122C21.1  ENSG00000253901      lincRNA
410   RP11-239H6.2  ENSG00000227803    antisense
411    RP1-12G14.7  ENSG00000233330    antisense
412  RP11-466P24.6  ENSG00000250348    antisense
413  RP11-503N18.1  ENSG00000206113      lincRNA
414  RP13-507P19.2  ENSG00000230294      lincRNA
448    SPANXA2-OT1  ENSG00000277215      lincRNA

NOTES- WHICH GENE NAMES TO CHNGE BY THE ORDER IN THE ABOVE LIST (STARTING FROM 1-31)
- 2-PKP4-AS1
- 3-no name (keep as it is)
- 4-ACOXL-AS1
- 6-PCBP3-AS1
- 7-LINC02897
- 9-EPCIP-AS1
- 10-CDRT15P3
- 12-no name (keep as it is)
- 13-FAM27E5
- 15-LINC02076
- 16-FAM30A
- 17-CYTOR
- 25-no name (keep as it is)
- 26-no name (keep as it is)
- 27-no name (keep as it is)
- 28-no name (keep as it is)
- 29-CFAP99
- 30-LINC02370

In [51]:
#CHANGE GENE NAMES:
hsg_new.loc[hsg_new.ens=='ENSG00000204380','gene']='PKP4-AS1'
hsg_new.loc[hsg_new.ens=='ENSG00000204581','gene']='ACOXL-AS1'
hsg_new.loc[hsg_new.ens=='ENSG00000205424','gene']='PCBP3-AS1'
hsg_new.loc[hsg_new.ens=='ENSG00000221953','gene']='LINC02897'
hsg_new.loc[hsg_new.ens=='ENSG00000205930','gene']='EPCIP-AS1'
hsg_new.loc[hsg_new.ens=='ENSG00000186825','gene']='CDRT15P3'
hsg_new.loc[hsg_new.ens=='ENSG00000178130','gene']='FAM27E5'
hsg_new.loc[hsg_new.ens=='ENSG00000220161','gene']='LINC02076'
hsg_new.loc[hsg_new.ens=='ENSG00000226777','gene']='FAM30A'
hsg_new.loc[hsg_new.ens=='ENSG00000222041','gene']='CYTOR'
hsg_new.loc[hsg_new.ens=='ENSG00000206113','gene']='CFAP99'
hsg_new.loc[hsg_new.ens=='ENSG00000230294','gene']='LINC02370'
#finally change lincrns to lncrna to avoid confusion
hsg_new.loc[hsg_new["Annotated as"]=="lincRNA",'Annotated as']="lncRNA"
#avoid warnings

/tmp/ipykernel_1822071/3712315008.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hsg_new.loc[hsg_new.ens=='ENSG00000204380','gene']='PKP4-AS1'
/tmp/ipykernel_1822071/3712315008.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hsg_new.loc[hsg_new.ens=='ENSG00000204581','gene']='ACOXL-AS1'
/tmp/ipykernel_1822071/3712315008.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hsg_new.loc[hsg_new.ens=='ENSG00000205424','gene']='PCBP3-AS1'
/tmp/ipykernel_1822071/3712315008.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hsg_new.loc[hsg_new.ens=='ENSG00000221953','gene']='LINC02897'
/tmp/ipykernel_1822071/3712315008.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hsg_new.loc[hsg_new.ens=='ENSG00000205930','gene']='EPCIP-AS1'
/tmp/ipykernel_1822071/3712315008.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hsg_new.loc[hsg_new.ens=='ENSG00000186825','gene']='CDRT15P3'
/tmp/ipykernel_1822071/3712315008.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hsg_new.loc[hsg_new.ens=='ENSG00000178130','gene']='FAM27E5'
/tmp/ipykernel_1822071/3712315008.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hsg_new.loc[hsg_new.ens=='ENSG00000220161','gene']='LINC02076'
/tmp/ipykernel_1822071/3712315008.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hsg_new.loc[hsg_new.ens=='ENSG00000226777','gene']='FAM30A'
/tmp/ipykernel_1822071/3712315008.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hsg_new.loc[hsg_new.ens=='ENSG00000222041','gene']='CYTOR'
/tmp/ipykernel_1822071/3712315008.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hsg_new.loc[hsg_new.ens=='ENSG00000206113','gene']='CFAP99'
/tmp/ipykernel_1822071/3712315008.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hsg_new.loc[hsg_new.ens=='ENSG00000230294','gene']='LINC02370'
/tmp/ipykernel_1822071/3712315008.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hsg_new.loc[hsg_new["Annotated as"]=="lincRNA",'Annotated as']="lncRNA"

## add duplicated genes

##### we add here duplicated genes from 2 sources that talk about segmental duplications:
<ol>
    <li>https://pubmed.ncbi.nlm.nih.gov/28580430/ (the bigger list)</li>
    <li>https://pmc.ncbi.nlm.nih.gov/articles/PMC6169893/#sec19</li>
</ol>

In [109]:
hsg_dup=pd.read_csv("/scratch200/reutj/data/hsg_gene_lists/duplicated_by_region.csv")

In [110]:
hsg_dup

      Region                                              Genes
0       1p12                    FCGR1C,HIST2H2BC,FAM72C,SRGAP2C
1     1q21.1  FCGR1D,HIST2H2BD,SRGAP2D,FAM72D,FAM72B,SRGAP2B...
2     1q32.1                                     FAM72A,SRGAP2A
3     2p11.2                                    CD8B-A,MIR4435B
4       2q13                  CD8B-B,MIR4267A,MIR4267B,MIR4435A
5     2q21.1                        CFC1B,TISP43B,TISP43A,CFC1A
6       5q13  OCLN,GTF2H2C,NAIPC,SERF1B,SMN2,GTF2H2B,NAIPB,S...
7     6p25.3                                            DUSP22A
8    7q11.23  GTF2IC,NCF1C,GTF2IDR2C,GTF2IA,NCF1A,GTF2IRD2A,...
9       7q35  TCAF1A,TCAF2B,TCAF2C,TCAF2A,TCAF1B,ARHGEF5C,OR...
10     10q11  GPRIN2B,NPY4RB,PTPN20B,FRMPD2B,NPY4RA,GPRIN2A,...
11   15q13.3                CHRFAM7A,ARHGAP11B,CHRNA7,ARHGAP11A
12   16p11.2                                      BOLA2A,BOLA2B
13   16q22.2                                              HYDIN
14  18p11.32                                             ROCK1B
15   18q11.1                                             ROCK1A

In [111]:
dup_gene_names=[]
for i in hsg_dup["Genes"].tolist():
    dup_gene_names.extend(i.split(","))

In [113]:
#this is the list from the first duplicated article we looked at (find)
hsgenes2=["SRGAP2","SRGAP2B","SRGAP2C","HYDIN","HYDIN2","ARHGAP11A","ARHGAP11B","FRMPD2","FRMPD2B"
            ,"SRGAP2D","FAM72A","FAM72B","FAM72C","FAM72D","ROCK1","ROCK1P1","PTPN20","PTPN20CP","GTF2I","GTF2IP1","GTF2IP4"
            ,"GTF2IRD2","GTF2IRD2B","GTF2IRD2P1" ,"NCF1","NCF1C","NCF1B","GPR89A","GPR89B","CD8B","CD8B2"
            ,"NOTCH2","NOTCH2NL","NOTCH2NLB","NOTCH2NLC","NOTCH2NLD","CORO1A","CORO1AP","SLX1A","SLX1B"
            ,"BOLA2B","BOLA2","FCGR1A","FCGR1B","FCGR1CP","ARHGEF34P","ARHGEF35","ARHGEF5","CHRFAM7A","CHRNA7"]

In [116]:
dup_gene_names=list(set(dup_gene_names)|set(hsgenes2))
dup_gene_names.sort()

In [122]:
#genes_to_add
dup_genes_to_add=[i for i in dup_gene_names if i not in hsg_new.gene.tolist()]
dup_genes_to_add

['ARHGEF34P',
 'ARHGEF35',
 'ARHGEF5A',
 'ARHGEF5B',
 'ARHGEF5C',
 'BOLA2A',
 'BOLA2B',
 'CD8B-A',
 'CD8B-B',
 'CD8B2',
 'CFC1A',
 'CORO1AP',
 'DUSP22A',
 'FAM72B',
 'FCGR1B',
 'FCGR1C',
 'FCGR1CP',
 'FCGR1D',
 'FRMPD2A',
 'FRMPD2B',
 'GPR89A',
 'GPR89B',
 'GPRIN2A',
 'GPRIN2B',
 'GTF2H2B',
 'GTF2IA',
 'GTF2IB',
 'GTF2IC',
 'GTF2IDR2C',
 'GTF2IP1',
 'GTF2IP4',
 'GTF2IRD2A',
 'GTF2IRD2B',
 'GTF2IRD2P1',
 'HIST2H2BA',
 'HIST2H2BC',
 'HIST2H2BD',
 'HYDIN2',
 'MIR4267A',
 'MIR4267B',
 'MIR4435A',
 'MIR4435B',
 'NAIPB',
 'NAIPC',
 'NAIPD',
 'NCF1A',
 'NCF1B',
 'NCF1C',
 'NOTCH2',
 'NOTCH2NLB',
 'NOTCH2NLC',
 'NOTCH2NLD',
 'NPY4RA',
 'NPY4RB',
 'OCLNB',
 'OR2A-A',
 'OR2A-B',
 'PTPN20',
 'PTPN20B',
 'PTPN20CP',
 'ROCK1A',
 'ROCK1B',
 'ROCK1P1',
 'SRGAP2A',
 'SRGAP2D',
 'TCAF1A',
 'TCAF1B',
 'TCAF2A',
 'TCAF2B',
 'TCAF2C',
 'TISP43A',
 'TISP43B']

* now we will receive the ens for all of those, it may be that genes appear twice or their naming is incorrect here so its a good time to check that:

In [ ]:
import mygene

mg = mygene.MyGeneInfo()

In [125]:
res=pd.DataFrame(mg.querymany(dup_genes_to_add, scopes='symbol', fields='ensembl.gene', species='human'))
res

Input sequence provided is already in string format. No operation performed
Input sequence provided is already in string format. No operation performed
12 input query terms found dup hits:	[('ARHGEF34P', 2), ('FRMPD2B', 2), ('GTF2H2B', 2), ('GTF2IP1', 2), ('GTF2IP4', 2), ('HYDIN2', 2), ('
47 input query terms found no hit:	['ARHGEF5A', 'ARHGEF5B', 'ARHGEF5C', 'BOLA2A', 'CD8B-A', 'CD8B-B', 'CFC1A', 'CORO1AP', 'DUSP22A', 'F

,query,_id,_score,ensembl,notfound
0,ARHGEF34P,ENSG00000204959,8.505431,{'gene': 'ENSG00000204959'},NaN
1,ARHGEF34P,728377,8.505431,NaN,NaN
2,ARHGEF35,445328,24.663984,"[{'gene': 'ENSG00000288422'}, {'gene': 'ENSG00...",NaN
3,ARHGEF5A,NaN,NaN,NaN,True
4,ARHGEF5B,NaN,NaN,NaN,True
...,...,...,...,...,...
79,TCAF2B,NaN,NaN,NaN,True
80,TCAF2C,ENSG00000283528,25.455769,{'gene': 'ENSG00000283528'},NaN
81,TCAF2C,100533814,25.455769,NaN,NaN
82,TISP43A,NaN,NaN,NaN,True
83,TISP43B,NaN,NaN,NaN,True

In [130]:
#genes with hit
#notice there are genes that appear twice
res[res.ensembl.isna()==False]

,query,_id,_score,ensembl,notfound
0,ARHGEF34P,ENSG00000204959,8.505431,{'gene': 'ENSG00000204959'},NaN
2,ARHGEF35,445328,24.663984,"[{'gene': 'ENSG00000288422'}, {'gene': 'ENSG00...",NaN
7,BOLA2B,654483,19.083899,{'gene': 'ENSG00000169627'},NaN
10,CD8B2,927,27.158619,{'gene': 'ENSG00000254126'},NaN
14,FAM72B,653820,25.845304,{'gene': 'ENSG00000188610'},NaN
17,FCGR1CP,100132417,8.760845,{'gene': 'ENSG00000265531'},NaN
20,FRMPD2B,728798,8.505431,{'gene': 'ENSG00000293529'},NaN
21,FRMPD2B,ENSG00000150175,8.505431,{'gene': 'ENSG00000150175'},NaN
22,GPR89A,653519,20.248370,{'gene': 'ENSG00000117262'},NaN
23,GPR89B,51463,19.633924,{'gene': 'ENSG00000188092'},NaN
26,GTF2H2B,ENSG00000226259,8.505431,{'gene': 'ENSG00000226259'},NaN
32,GTF2IP1,2970,8.505431,{'gene': 'ENSG00000290871'},NaN
33,GTF2IP1,ENSG00000277053,8.505431,{'gene': 'ENSG00000277053'},NaN
34,GTF2IP4,100093631,8.505431,{'gene': 'ENSG00000293241'},NaN
35,GTF2IP4,ENSG00000233369,8.505431,{'gene': 'ENSG00000233369'},NaN
37,GTF2IRD2B,389524,22.254301,{'gene': 'ENSG00000174428'},NaN
38,GTF2IRD2P1,401375,8.760845,{'gene': 'ENSG00000214544'},NaN
42,HYDIN2,ENSG00000276975,8.505431,{'gene': 'ENSG00000276975'},NaN
52,NCF1B,654816,8.505431,{'gene': 'ENSG00000290838'},NaN
53,NCF1B,ENSG00000182487,8.505431,{'gene': 'ENSG00000182487'},NaN
54,NCF1C,654817,8.337195,{'gene': 'ENSG00000296524'},NaN
55,NCF1C,ENSG00000165178,8.337195,{'gene': 'ENSG00000165178'},NaN
56,NOTCH2,4853,17.777860,{'gene': 'ENSG00000134250'},NaN
57,NOTCH2NLB,100996763,27.158619,{'gene': 'ENSG00000286019'},NaN
58,NOTCH2NLC,100996717,27.158619,{'gene': 'ENSG00000286219'},NaN
65,PTPN20,26095,18.051006,{'gene': 'ENSG00000204179'},NaN
67,PTPN20CP,653045,8.505431,{'gene': 'ENSG00000290899'},NaN
68,PTPN20CP,ENSG00000278561,8.505431,{'gene': 'ENSG00000278561'},NaN
71,ROCK1P1,727758,8.505431,{'gene': 'ENSG00000290877'},NaN
72,ROCK1P1,ENSG00000263006,8.505431,{'gene': 'ENSG00000263006'},NaN
74,SRGAP2D,ENSG00000270872,8.505431,{'gene': 'ENSG00000270872'},NaN
80,TCAF2C,ENSG00000283528,25.455769,{'gene': 'ENSG00000283528'},NaN

In [208]:
#function to gather the hits for each gene together 
dup_dict={}
for i in range(len(res)):
    gene=res['query'][i]
    dup_dict[gene]=[]
for i in range(len(res)):
    gene=res['query'][i]
    ens=res.ensembl[i]
    if type(ens)==dict:
        dup_dict[gene].append(ens['gene'])
    elif type(ens)==list:
        dup_dict[gene]=ens

dup_dict

{'ARHGEF34P': ['ENSG00000204959'],
 'ARHGEF35': [{'gene': 'ENSG00000288422'}, {'gene': 'ENSG00000213214'}],
 'ARHGEF5A': [],
 'ARHGEF5B': [],
 'ARHGEF5C': [],
 'BOLA2A': [],
 'BOLA2B': ['ENSG00000169627'],
 'CD8B-A': [],
 'CD8B-B': [],
 'CD8B2': ['ENSG00000254126'],
 'CFC1A': [],
 'CORO1AP': [],
 'DUSP22A': [],
 'FAM72B': ['ENSG00000188610'],
 'FCGR1B': [],
 'FCGR1C': [],
 'FCGR1CP': ['ENSG00000265531'],
 'FCGR1D': [],
 'FRMPD2A': [],
 'FRMPD2B': ['ENSG00000293529', 'ENSG00000150175'],
 'GPR89A': ['ENSG00000117262'],
 'GPR89B': ['ENSG00000188092'],
 'GPRIN2A': [],
 'GPRIN2B': [],
 'GTF2H2B': ['ENSG00000226259'],
 'GTF2IA': [],
 'GTF2IB': [],
 'GTF2IC': [],
 'GTF2IDR2C': [],
 'GTF2IP1': ['ENSG00000290871', 'ENSG00000277053'],
 'GTF2IP4': ['ENSG00000293241', 'ENSG00000233369'],
 'GTF2IRD2A': [],
 'GTF2IRD2B': ['ENSG00000174428'],
 'GTF2IRD2P1': ['ENSG00000214544'],
 'HIST2H2BA': [],
 'HIST2H2BC': [],
 'HIST2H2BD': [],
 'HYDIN2': ['ENSG00000276975'],
 'MIR4267A': [],
 'MIR4267B': [],
 'MIR4435A': [],
 'MIR4435B': [],
 'NAIPB': [],
 'NAIPC': [],
 'NAIPD': [],
 'NCF1A': [],
 'NCF1B': ['ENSG00000290838', 'ENSG00000182487'],
 'NCF1C': ['ENSG00000296524', 'ENSG00000165178'],
 'NOTCH2': ['ENSG00000134250'],
 'NOTCH2NLB': ['ENSG00000286019'],
 'NOTCH2NLC': ['ENSG00000286219'],
 'NOTCH2NLD': [],
 'NPY4RA': [],
 'NPY4RB': [],
 'OCLNB': [],
 'OR2A-A': [],
 'OR2A-B': [],
 'PTPN20': ['ENSG00000204179'],
 'PTPN20B': [],
 'PTPN20CP': ['ENSG00000290899', 'ENSG00000278561'],
 'ROCK1A': [],
 'ROCK1B': [],
 'ROCK1P1': ['ENSG00000290877', 'ENSG00000263006'],
 'SRGAP2A': [],
 'SRGAP2D': ['ENSG00000270872'],
 'TCAF1A': [],
 'TCAF1B': [],
 'TCAF2A': [],
 'TCAF2B': [],
 'TCAF2C': ['ENSG00000283528'],
 'TISP43A': [],
 'TISP43B': []}

In [214]:
#present as a dataframe
pd.DataFrame.from_dict(dup_dict,orient='index').iloc[30:,]

                          0                1
GTF2IP4     ENSG00000293241  ENSG00000233369
GTF2IRD2A              None             None
GTF2IRD2B   ENSG00000174428             None
GTF2IRD2P1  ENSG00000214544             None
HIST2H2BA              None             None
HIST2H2BC              None             None
HIST2H2BD              None             None
HYDIN2      ENSG00000276975             None
MIR4267A               None             None
MIR4267B               None             None
MIR4435A               None             None
MIR4435B               None             None
NAIPB                  None             None
NAIPC                  None             None
NAIPD                  None             None
NCF1A                  None             None
NCF1B       ENSG00000290838  ENSG00000182487
NCF1C       ENSG00000296524  ENSG00000165178
NOTCH2      ENSG00000134250             None
NOTCH2NLB   ENSG00000286019             None
NOTCH2NLC   ENSG00000286219             None
NOTCH2NLD              None             None
NPY4RA                 None             None
NPY4RB                 None             None
OCLNB                  None             None
OR2A-A                 None             None
OR2A-B                 None             None
PTPN20      ENSG00000204179             None
PTPN20B                None             None
PTPN20CP    ENSG00000290899  ENSG00000278561
ROCK1A                 None             None
ROCK1B                 None             None
ROCK1P1     ENSG00000290877  ENSG00000263006
SRGAP2A                None             None
SRGAP2D     ENSG00000270872             None
TCAF1A                 None             None
TCAF1B                 None             None
TCAF2A                 None             None
TCAF2B                 None             None
TCAF2C      ENSG00000283528             None
TISP43A                None             None
TISP43B                None             None

In [215]:
dups_in_data=dict([(i,hsg_new.ens[hsg_new.gene==i].to_string(index = False)) for i in dup_gene_names if i in hsg_new.gene.tolist()])
dups_in_data

{'ARHGAP11A': 'ENSG00000198826',
 'ARHGAP11B': 'ENSG00000187951',
 'ARHGEF5': 'ENSG00000050327',
 'BOLA2': 'ENSG00000183336',
 'CD8B': 'ENSG00000172116',
 'CFC1B': 'ENSG00000152093',
 'CHRFAM7A': 'ENSG00000166664',
 'CHRNA7': 'ENSG00000175344',
 'CORO1A': 'ENSG00000102879',
 'FAM72A': 'ENSG00000196550',
 'FAM72C': 'ENSG00000263513',
 'FAM72D': 'ENSG00000215784',
 'FCGR1A': 'ENSG00000150337',
 'FRMPD2': 'ENSG00000170324',
 'GTF2H2': 'ENSG00000145736',
 'GTF2H2C': 'ENSG00000183474',
 'GTF2I': 'ENSG00000263001',
 'GTF2IRD2': 'ENSG00000196275',
 'HYDIN': 'ENSG00000157423',
 'NAIP': 'ENSG00000249437',
 'NCF1': 'ENSG00000158517',
 'NOTCH2NL': 'ENSG00000213240',
 'OCLN': 'ENSG00000197822',
 'PTPN20A': 'ENSG00000204179',
 'ROCK1': 'ENSG00000067900',
 'SERF1A': 'ENSG00000172058',
 'SERF1B': 'ENSG00000205572',
 'SLX1A': 'ENSG00000132207',
 'SLX1B': 'ENSG00000181625',
 'SMN1': 'ENSG00000172062',
 'SMN2': 'ENSG00000205571',
 'SRGAP2': 'ENSG00000266028',
 'SRGAP2B': 'ENSG00000196369',
 'SRGAP2C': 'ENSG00000171943'}

<b>now to look at it more clearly I moved dups in data and dup_dict into an empty excel sheet to distinguish between gene familis, ancestral and so on..
there, I have looked at each gene against gene cards and the other gene names from each family and in the original excel tables from the duplicated gene families papers to determine which is ancestral which dup and which gene do not exist or its naming is wrong. 
eventully I arranges all genes according to their families to create organised dup table with ensg</b>
<p>note some genes do not have ensg but the ancestral or other gene representatives have, only genes with ensg will be relevant in this project</p>

<h3> Overall changes in gene names from sup_dict to the organized table </h3>	
	
* arhgef5a- is arhgef5
* arhgef5b-arhgef35
* arhgef5c-arhgef34p
* BOLA2A -bola2	
* CD8B-A-cd8a
* CD8B-B-cd8b
* cfc1a-cfc1
* FRMPD2a-FRMPD2
* GTF2IA-GTF2I
* GTF2IB,GTF2IC-	not real gene names 
* SRGAP2A-srgap2
* all miRNA- no ens	
* NCF1A-ncf1
* ROCK1B-rock1p1
* TIPS43A-TIPS43
* TCAF1A-TCAF1
* tcaf2a-tcaf2
* DUSP22A-dusp22
* FCGR1C-FCGR1CP
* FCGR1B-FCGR1BP
* PTPN20A-PTPN20
* GPRIN2A-GPRIN2
* FCGR1D-FCGR1CP
* GTF2IRD2A-GTF2IRD2
* HIST2H2BA-H2BP1
* HIST2H2BC-H2BC20P
* HIST2H2BD-H2BC19P
* NPY4RA-NPY4R
* NPY4RB-NPY4R2
* OCLNB-OCLNP1
* OR2A-A-OR2A1

In [2]:
## upload the complete human organised diplicate gene list
dup_complete=pd.read_csv("/scratch200/reutj/data/hsg_gene_lists/duplicates_hsg_organized.csv")

In [3]:
dup_complete

,gene,ens,ancestral,notes
0,ARHGAP11A,ENSG00000198826,ancestral,NaN
1,ARHGAP11B,ENSG00000187951,duplicate,NaN
2,ARHGEF5,ENSG00000050327,ancestral,"cnvs more in human genome, but no duplicates k..."
3,ARHGEF34P,ENSG00000204959,duplicate,NaN
4,ARHGEF35,ENSG00000213214,duplicate,NaN
...,...,...,...,...
79,TCAF2,ENSG00000170379,ancestral,NaN
80,TCAF2B,NaN,duplicate,duplicate not appearing in gene cards
81,TCAF2C,ENSG00000283528,duplicate,NaN
82,TISP43,ENSG00000183292,ancestral,NaN
83,TISP43B,NaN,duplicate,duplicate not appearing in gene cards

In [8]:
#upload new_human_gene_list_forcomparison..
hsg_up=pd.read_csv("/scratch200/reutj/data/hsg_gene_lists/updated_human_specific_genes3.csv")
hsg_up

     Unnamed: 0       gene              ens    Annotated as
0             0    SEPTIN7  ENSG00000122545  protein_coding
1             1      AATBC  ENSG00000215458       antisense
2             2     ABCB10  ENSG00000135776  protein_coding
3             3     ABCC12  ENSG00000140798  protein_coding
4             4      ABCC6  ENSG00000091262  protein_coding
..          ...        ...              ...             ...
614         614     DUSP22  ENSG00000112679  protein_coding
615         615      GTF2I  ENSG00000263001  protein_coding
616         616  ARHGAP11A  ENSG00000198826  protein_coding
617         617       NCF1  ENSG00000158517  protein_coding
618         618     GPRIN2  ENSG00000204175  protein_coding

[619 rows x 4 columns]

### check duplicated genes 
ther idea here is to check duplicates gene families , because of the close similarities of the family memebrs in the duplicated groups if I see that the duplicated genes do not express in the data but the ancestral is and it is similar so we will put the ancestral for now
<br> also in gene families where duplicates dont have ensg, ancestral will be considered to begin with.. (?)

In [5]:
adata=sc.read_h5ad("/scratch200/reutj/data/updated_cortex_data_hg38.h5ad")

In [6]:
#former hsg_exp list
hsg_exp=pd.read_csv("/scratch200/reutj/data/hsg_gene_lists/hsg_exp_in_adata_cortex2.csv")
hsg_exp

,Unnamed: 0,gene,ens,Annotated as,num_cells_expressed,mean_expression
0,0,SEPTIN7,ENSG00000122545,protein_coding,263655,3.986133
1,1,AATBC,ENSG00000215458,antisense,302,1.019868
2,2,ABCB10,ENSG00000135776,protein_coding,34502,1.295606
3,3,ABCC12,ENSG00000140798,protein_coding,296,1.074324
4,4,ABCC6,ENSG00000091262,protein_coding,1554,1.072716
...,...,...,...,...,...,...
533,533,LINC02073,ENSG00000267452,lncRNA,2,1.000000
534,534,LINC00868,ENSG00000267535,lncRNA,59,1.101695
535,535,LINC02712,ENSG00000273409,lncRNA,242,1.095041
536,536,AL360294.1/PP2672,ENSG00000279261,lncRNA,0,0.000000
537,537,LINC00602,ENSG00000281832,lncRNA,136,1.000000

In [15]:
#find genes that do not appear here and in the original hsg list and check their exp level:
dup_wensemble=dup_complete[dup_complete.ens.isna()==False]
dups_to_check=[i for i in dup_wensemble.gene.tolist() if i not in hsg_exp.gene.tolist()]
dups_to_check_ens=dup_wensemble.loc[dup_wensemble.gene.isin(dups_to_check),'ens']

In [19]:
### results dictionary for ensg

results_ens = {"gene": [], "num_cells_expressed": [], "mean_expression": []}

# Loop through each gene in the list
hsens=dups_to_check_ens.tolist()
ens_adata=adata.var.Accession.tolist()
for gene in hsens:
    if gene in ens_adata:
        print(gene)
        ind= ens_adata.index(gene)
        print(ind)
        # Get expression data for the gene from counts layer
        gene_counts = adata.X[:,ind].toarray().flatten()
        
        # Count cells with expression > 0
        num_cells_expressed = np.sum(gene_counts > 0)
        
        # Calculate mean expression for cells with expression > 0
        mean_expression = gene_counts[gene_counts > 0].mean() if num_cells_expressed > 0 else 0
        
        # Store results
        results_ens["gene"].append(gene)
        results_ens["num_cells_expressed"].append(num_cells_expressed)
        results_ens["mean_expression"].append(mean_expression)
    else:
        print(f"{gene} is not in adata")

ENSG00000198826
26611
ENSG00000187951 is not in adata
ENSG00000050327
30908
ENSG00000204959 is not in adata
ENSG00000169627
16586
ENSG00000172116
32946
ENSG00000175344
19511
ENSG00000152093
338
ENSG00000102879
19980
ENSG00000172725
26301
ENSG00000112679
23068
ENSG00000196550
25197
ENSG00000150337
28955
ENSG00000198019
3578
ENSG00000265531 is not in adata
ENSG00000170324
5826
ENSG00000150175 is not in adata
ENSG00000117262
23425
ENSG00000145736
27222
ENSG00000226259 is not in adata
ENSG00000263001
24164
ENSG00000277053 is not in adata
ENSG00000233369 is not in adata
ENSG00000196275
19614
ENSG00000214544 is not in adata
ENSG00000223345 is not in adata
ENSG00000261716 is not in adata
ENSG00000220323 is not in adata
ENSG00000157423
1366
ENSG00000276975 is not in adata
ENSG00000249437
21191
ENSG00000158517
30067
ENSG00000182487 is not in adata
ENSG00000165178 is not in adata
ENSG00000134250
20530
ENSG00000286019 is not in adata
ENSG00000286219 is not in adata
ENSG00000264717
6688
ENSG00000230847 is not in adata
ENSG00000204179
3296
ENSG00000278561 is not in adata
ENSG00000067900
22714
ENSG00000263006 is not in adata
ENSG00000172058
5964
ENSG00000132207
13473
ENSG00000172062
26327
ENSG00000266028
23834
ENSG00000270872 is not in adata
ENSG00000198420
20145
ENSG00000183292
10983

In [26]:
int(hsg_exp.num_cells_expressed[hsg_exp.ens=="ENSG00000213214"])

/tmp/ipykernel_1822071/1951432226.py:1: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  int(hsg_exp.num_cells_expressed[hsg_exp.ens=="ENSG00000213214"])

173

In [33]:
#unite dup genes exp in cortex data together:
dup_exp=[]
for i in dup_complete.ens.tolist():
    if i in hsg_exp.ens.tolist():
        dup_exp.append(int(hsg_exp.num_cells_expressed[hsg_exp.ens==i]))
    elif i in hsg_exp2.gene.tolist():
        dup_exp.append(int(hsg_exp2.num_cells_expressed[hsg_exp2.gene==i]))
    else:
        dup_exp.append(0)
dup_complete["num_exp_cells_cortex"]=dup_exp
dup_complete.iloc[:39,:]

#we dont see expression or not in the data

/tmp/ipykernel_1822071/2580330504.py:7: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  dup_exp.append(int(hsg_exp2.num_cells_expressed[hsg_exp2.gene==i]))
/tmp/ipykernel_1822071/2580330504.py:5: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  dup_exp.append(int(hsg_exp.num_cells_expressed[hsg_exp.ens==i]))

,gene,ens,ancestral,notes,num_exp_cells_cortex
0,ARHGAP11A,ENSG00000198826,ancestral,NaN,40577
1,ARHGAP11B,ENSG00000187951,duplicate,NaN,0
2,ARHGEF5,ENSG00000050327,ancestral,"cnvs more in human genome, but no duplicates k...",634
3,ARHGEF34P,ENSG00000204959,duplicate,NaN,0
4,ARHGEF35,ENSG00000213214,duplicate,NaN,173
5,BOLA2,ENSG00000183336,ancestral,NaN,104
6,BOLA2B,ENSG00000169627,duplicate,NaN,5373
7,CD8B,ENSG00000172116,ancestral,NaN,447
8,CD8B2,ENSG00000254126,duplicate,NaN,84
9,CHRNA7,ENSG00000175344,ancestral,NaN,19232
10,CHRFAM7A,ENSG00000166664,duplicate,NaN,1495
11,CFC1,ENSG00000136698,ancestral,NaN,0
12,CFC1B,ENSG00000152093,duplicate,NaN,3
13,CORO1A,ENSG00000102879,ancestral,NaN,47126
14,CORO1B,ENSG00000172725,duplicate,NaN,53536
15,DUSP22,ENSG00000112679,other,"cnvs more in human genome, but no duplicates k...",20241
16,FAM72A,ENSG00000196550,ancestral,NaN,4002
17,FAM72B,ENSG00000188610,duplicate,NaN,6000
18,FAM72C,ENSG00000263513,duplicate,NaN,8611
19,FAM72D,ENSG00000215784,duplicate,NaN,13306
20,FCGR1A,ENSG00000150337,ancestral,NaN,179
21,FCGR1BP,ENSG00000198019,duplicate,NaN,60
22,FCGR1CP,ENSG00000265531,duplicate,NaN,0
23,FRMPD2,ENSG00000170324,ancestral,NaN,220
24,FRMPD2B,ENSG00000150175,duplicate,NaN,0
25,GPR89A,ENSG00000117262,ancestral,NaN,43324
26,GPR89B,ENSG00000188092,duplicate,NaN,32937
27,GPRIN2,ENSG00000204175,ancestral,NaN,2169
28,GPRIN2B,NaN,duplicate,duplicate not appearing in gene cards,0
29,GTF2H2,ENSG00000145736,ancestral,NaN,42988
30,GTF2H2B,ENSG00000226259,duplicate,NaN,0
31,GTF2H2C,ENSG00000183474,duplicate,NaN,26106
32,GTF2I,ENSG00000263001,ancestral,NaN,169611
33,GTF2IP1,ENSG00000277053,duplicate,NaN,0
34,GTF2IP4,ENSG00000233369,duplicate,NaN,0
35,GTF2IRD2,ENSG00000196275,ancestral,NaN,25084
36,GTF2IRD2B,ENSG00000174428,duplicate,NaN,43603
37,GTF2IDR2C,NaN,duplicate,duplicate not appearing in gene cards,0
38,GTF2IRD2P1,ENSG00000214544,duplicate,NaN,0

In [34]:
dup_complete.iloc[39:,:]

,gene,ens,ancestral,notes,num_exp_cells_cortex
39,H2BP1,ENSG00000223345,ancestral,seems thare are much more duplicates than that...,0
40,H2BC19P,ENSG00000261716,duplicate,NaN,0
41,H2BC20P,ENSG00000220323,duplicate,NaN,0
42,HYDIN,ENSG00000157423,ancestral,NaN,21283
43,HYDIN2,ENSG00000276975,duplicate,NaN,0
44,NAIP,ENSG00000249437,ancestral,NaN,3095
45,NAIPB,NaN,duplicate,duplicate not appearing in gene cards,0
46,NAIPC,NaN,duplicate,duplicate not appearing in gene cards,0
47,NAIPD,NaN,duplicate,duplicate not appearing in gene cards,0
48,NCF1,ENSG00000158517,ancestral,NaN,273
49,NCF1B,ENSG00000182487,duplicate,NaN,0
50,NCF1C,ENSG00000165178,duplicate,NaN,0
51,NOTCH2,ENSG00000134250,ancestral,NaN,67763
52,NOTCH2NL,ENSG00000213240,ancestral,NaN,35
53,NOTCH2NLB,ENSG00000286019,duplicate,NaN,0
54,NOTCH2NLC,ENSG00000286219,duplicate,NaN,0
55,NOTCH2NLD,NaN,duplicate,duplicate not appearing in gene cards,0
56,NPY4R,ENSG00000204174,ancestral,NaN,2
57,NPY4R2,ENSG00000264717,duplicate,NaN,7
58,OCLN,ENSG00000197822,ancestral,NaN,1995
59,OCLNP1,ENSG00000230847,duplicate,NaN,0
60,OR2A1,ENSG00000221970,ancestral,NaN,33
61,OR2A-B,NaN,duplicate,duplicate not appearing in gene cards,0
62,PTPN20,ENSG00000204179,ancestral,NaN,7566
63,PTPN20B,NaN,duplicate,duplicate not appearing in gene cards,0
64,PTPN20CP,ENSG00000278561,duplicate,NaN,0
65,ROCK1,ENSG00000067900,ancestral,NaN,153011
66,ROCK1P1,ENSG00000263006,duplicate,NaN,0
67,SERF1A,ENSG00000172058,ancestral,NaN,3601
68,SERF1B,ENSG00000205572,duplicate,NaN,1287
69,SLX1A,ENSG00000132207,ancestral,NaN,806
70,SLX1B,ENSG00000181625,duplicate,NaN,713
71,SMN1,ENSG00000172062,ancestral,NaN,6372
72,SMN2,ENSG00000205571,duplicate,NaN,3993
73,SRGAP2,ENSG00000266028,ancestral,NaN,118717
74,SRGAP2B,ENSG00000196369,duplicate,NaN,62442
75,SRGAP2C,ENSG00000171943,duplicate,NaN,70404
76,SRGAP2D,ENSG00000270872,duplicate,NaN,0
77,TCAF1,ENSG00000198420,ancestral,NaN,63479
78,TCAF1B,NaN,duplicate,duplicate not appearing in gene cards,0
79,TCAF2,ENSG00000170379,ancestral,NaN,1234
80,TCAF2B,NaN,duplicate,duplicate not appearing in gene cards,0
81,TCAF2C,ENSG00000283528,duplicate,NaN,5
82,TISP43,ENSG00000183292,ancestral,NaN,44
83,TISP43B,NaN,duplicate,duplicate not appearing in gene cards,0

In [194]:
#conclusions:
#throw ancestral if duplicates appear in data
#throw gene families that dont have exp.. (exp - >100 cells) 
#throw ancestral which have exp or small exp and the dup appear in data but exp<100 cells
#in case dups do not appear in data but have ens (or at least some does..) keep just ancestral
#in case dups dont have ensemble at all- keep ancestral for now..
#tcaf2 family- keep ancestral althouh soem duplicate appear with many dew reads there is pne mpre duplicate that we dont know about


ancestrals_to_throw=["ARHGEF5","BOLA2","CHRNA7","CFC1","CORO1A","FAM72A","GPR89A","GTF2H2","GTF2IRD2","H2BP1","NPY4R","OR2A1","SERF1A","SLX1A",
                     "SMN1","SRGAP2","TISP43","CD8B","FCGR1A","NOTCH2NL"]
ancestrals_to_keep=["ARHGAP11A","FRMPD2","GTF2I","HYDIN","NCF1","OCLN","PTPN20","ROCK1","TCAF2"]
dups_to_throw=["ARHGAP11B","ARHGEF34P","CFC1B","FCGR1CP","FRMPD2B","GTF2H2B","GTF2IP1","GTF2IP4","GTF2IRD2P1","H2BC19P","H2BC20P","HYDIN2","NCF1B","NCF1C","NOTCH2NLB",
               "NOTCH2NLC","NOTCH2NLD","NPY4R2","OCLNP1","PTPN20CP","ROCK1P1","SRGAP2D","TCAF2C","CD8B2","FCGR1BP"]
ancestrals_throw_ens=dup_complete.loc[dup_complete.gene.isin(ancestrals_to_throw),'ens'].tolist()
dups_throw_ens=dup_complete.loc[dup_complete.gene.isin(dups_to_throw),'ens'].tolist()

In [195]:
#dup_genes_to_add_tofinaltable , for now..
dup_table_to_add=dup_wensemble[~(dup_wensemble.ens.isin(ancestrals_throw_ens) | dup_wensemble.ens.isin(dups_throw_ens))]
dup_table_to_add["Annotated as"]="protein_coding"
dup_table_to_add

/tmp/ipykernel_1822071/3790643467.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dup_table_to_add["Annotated as"]="protein_coding"

,gene,ens,ancestral,notes,Annotated as
0,ARHGAP11A,ENSG00000198826,ancestral,NaN,protein_coding
4,ARHGEF35,ENSG00000213214,duplicate,NaN,protein_coding
6,BOLA2B,ENSG00000169627,duplicate,NaN,protein_coding
10,CHRFAM7A,ENSG00000166664,duplicate,NaN,protein_coding
14,CORO1B,ENSG00000172725,duplicate,NaN,protein_coding
15,DUSP22,ENSG00000112679,other,"cnvs more in human genome, but no duplicates k...",protein_coding
17,FAM72B,ENSG00000188610,duplicate,NaN,protein_coding
18,FAM72C,ENSG00000263513,duplicate,NaN,protein_coding
19,FAM72D,ENSG00000215784,duplicate,NaN,protein_coding
23,FRMPD2,ENSG00000170324,ancestral,NaN,protein_coding
26,GPR89B,ENSG00000188092,duplicate,NaN,protein_coding
27,GPRIN2,ENSG00000204175,ancestral,NaN,protein_coding
31,GTF2H2C,ENSG00000183474,duplicate,NaN,protein_coding
32,GTF2I,ENSG00000263001,ancestral,NaN,protein_coding
36,GTF2IRD2B,ENSG00000174428,duplicate,NaN,protein_coding
42,HYDIN,ENSG00000157423,ancestral,NaN,protein_coding
44,NAIP,ENSG00000249437,ancestral,NaN,protein_coding
48,NCF1,ENSG00000158517,ancestral,NaN,protein_coding
51,NOTCH2,ENSG00000134250,ancestral,NaN,protein_coding
58,OCLN,ENSG00000197822,ancestral,NaN,protein_coding
62,PTPN20,ENSG00000204179,ancestral,NaN,protein_coding
65,ROCK1,ENSG00000067900,ancestral,NaN,protein_coding
68,SERF1B,ENSG00000205572,duplicate,NaN,protein_coding
70,SLX1B,ENSG00000181625,duplicate,NaN,protein_coding
72,SMN2,ENSG00000205571,duplicate,NaN,protein_coding
74,SRGAP2B,ENSG00000196369,duplicate,NaN,protein_coding
75,SRGAP2C,ENSG00000171943,duplicate,NaN,protein_coding
77,TCAF1,ENSG00000198420,ancestral,NaN,protein_coding
79,TCAF2,ENSG00000170379,ancestral,NaN,protein_coding

In [297]:
#create joined hsg list
hsg_wo_dups=hsg_new[~(hsg_new.ens.isin(dup_complete.ens.tolist()))]
hsg_all=pd.concat([hsg_wo_dups,dup_table_to_add.loc[:,['gene','ens','Annotated as']]])

In [298]:
hsg_all=hsg_all.drop_duplicates(subset=["gene", "ens"])
hsg_all=hsg_all[~(hsg_all["Annotated as"]=="polymorphic_pseudogene")] #remove more pseudogenes..
hsg_all

       gene              ens    Annotated as
0   SEPTIN7  ENSG00000122545  protein_coding
1     AATBC  ENSG00000215458       antisense
2    ABCB10  ENSG00000135776  protein_coding
3    ABCC12  ENSG00000140798  protein_coding
4     ABCC6  ENSG00000091262  protein_coding
..      ...              ...             ...
72     SMN2  ENSG00000205571  protein_coding
74  SRGAP2B  ENSG00000196369  protein_coding
75  SRGAP2C  ENSG00000171943  protein_coding
77    TCAF1  ENSG00000198420  protein_coding
79    TCAF2  ENSG00000170379  protein_coding

[573 rows x 3 columns]

In [300]:
hsg_all[hsg_all.gene.duplicated(keep=False)]

        gene              ens          Annotated as
73    CFAP99  ENSG00000249428        protein_coding
101  DEFB130  ENSG00000232948        protein_coding
102  DEFB130  ENSG00000233050        protein_coding
137  FAM95B1  ENSG00000223839                lncRNA
138  FAM95B1  ENSG00000274628  processed_transcript
328    OR4M2  ENSG00000182974        protein_coding
329    OR4M2  ENSG00000274102        protein_coding
371  POLR2J2  ENSG00000228049        protein_coding
372  POLR2J2  ENSG00000267645        protein_coding
413   CFAP99  ENSG00000206113                lncRNA
439  SNORA12  ENSG00000212175                snoRNA
440  SNORA12  ENSG00000212342                snoRNA
441  SNORA12  ENSG00000212464                snoRNA
469    SYT15  ENSG00000204176        protein_coding
470    SYT15  ENSG00000277758        protein_coding
516  ZNF286A  ENSG00000187607        protein_coding
517  ZNF286A  ENSG00000255104        protein_coding

##### changes:
* DEFB130-DEFB130A(1),DEFB130B(2)
* FAM95B1-CYP4F59P(2)
* OR4M2-OR4M2B(1)
* POLR2J2- second gene weird through rna gene, can drop
* CFAP99- first one not in gene cards
* SNORA12- LOC124900537(1),LOC124900269(2)
* SYT15- SYT15B (2)
* ZNF286A- second gene weird through rna gene, can drop

In [301]:
hsg_all.loc[101,"gene"]="DEFB130A"
hsg_all.loc[102,"gene"]="DEFB130B"
hsg_all.loc[138,"gene"]="CYP4F59P"
hsg_all.loc[328,"gene"]="OR4M2B"
hsg_all.loc[439,"gene"]="LOC124900537"
hsg_all.loc[440,"gene"]="LOC124900269"
hsg_all.loc[470,"gene"]="SYT15B"

In [302]:
hsg_all=hsg_all.drop([372,73,517]).reset_index()

In [303]:
hsg_all=hsg_all.drop(columns=['index'])
hsg_all

        gene              ens    Annotated as
0    SEPTIN7  ENSG00000122545  protein_coding
1      AATBC  ENSG00000215458       antisense
2     ABCB10  ENSG00000135776  protein_coding
3     ABCC12  ENSG00000140798  protein_coding
4      ABCC6  ENSG00000091262  protein_coding
..       ...              ...             ...
565     SMN2  ENSG00000205571  protein_coding
566  SRGAP2B  ENSG00000196369  protein_coding
567  SRGAP2C  ENSG00000171943  protein_coding
568    TCAF1  ENSG00000198420  protein_coding
569    TCAF2  ENSG00000170379  protein_coding

[570 rows x 3 columns]

In [127]:
hsg_exp2=hsg_exp2.rename(columns={'gene':'ens'})
hsg_exp2["gene"]=[dup_wensemble.gene[dup_wensemble.ens==i].to_string(index=False) for i in hsg_exp2.ens.tolist()]

In [305]:
#create joined hsg exp table
hsg_exp1=hsg_exp.loc[hsg_exp.ens.isin(hsg_all.ens.tolist()),['gene','ens','num_cells_expressed','mean_expression']]
hsg_exp_all=pd.concat([hsg_exp1,hsg_exp2[hsg_exp2.ens.isin(hsg_all.ens.tolist())]])
hsg_exp_all=hsg_exp_all.drop_duplicates(subset=["gene", "ens"])
hsg_exp_all

       gene              ens  num_cells_expressed  mean_expression
0   SEPTIN7  ENSG00000122545               263655         3.986133
1     AATBC  ENSG00000215458                  302         1.019868
2    ABCB10  ENSG00000135776                34502         1.295606
3    ABCC12  ENSG00000140798                  296         1.074324
4     ABCC6  ENSG00000091262                 1554         1.072716
..      ...              ...                  ...              ...
19     NCF1  ENSG00000158517                  273         1.014652
20   NOTCH2  ENSG00000134250                67763         1.889468
22   PTPN20  ENSG00000204179                 7566         1.137193
23    ROCK1  ENSG00000067900               153011         1.945592
28    TCAF1  ENSG00000198420                63479         1.409726

[526 rows x 4 columns]

In [306]:
hsg_exp_all[hsg_exp_all.num_cells_expressed	>100]

       gene              ens  num_cells_expressed  mean_expression
0   SEPTIN7  ENSG00000122545               263655         3.986133
1     AATBC  ENSG00000215458                  302         1.019868
2    ABCB10  ENSG00000135776                34502         1.295606
3    ABCC12  ENSG00000140798                  296         1.074324
4     ABCC6  ENSG00000091262                 1554         1.072716
..      ...              ...                  ...              ...
19     NCF1  ENSG00000158517                  273         1.014652
20   NOTCH2  ENSG00000134250                67763         1.889468
22   PTPN20  ENSG00000204179                 7566         1.137193
23    ROCK1  ENSG00000067900               153011         1.945592
28    TCAF1  ENSG00000198420                63479         1.409726

[406 rows x 4 columns]

In [307]:
#save to files..
hsg_all.to_csv("/scratch200/reutj/data/hsg_gene_lists/updated_hsg_list.csv")
hsg_exp_all.to_csv("/scratch200/reutj/data/hsg_gene_lists/hsg_exp_in_adata_cortex3.csv")

In [308]:
#save to saparate duplicates and non duplicates hsg files:
#dup genes from big table
dup_genes_big=hsg_big_filt.loc[hsg_big_filt["General Mechanism of Origin"]=="gene amplification","ens"]
dup_genes_big=dup_genes_big[~(dup_genes_big.isin(ancestrals_throw_ens) | dup_genes_big.isin(dups_throw_ens))].tolist()
#dup genes from new table
dup_genes_toadd=dup_table_to_add.ens[~(dup_table_to_add.ens.isin(dup_genes_big))].tolist()
for i in dup_genes_toadd:
    dup_genes_big.append(i)
print(len(dup_genes_big))

hsg_dup=hsg_all[hsg_all.ens.isin(dup_genes_big)]
hsg_dup

316

        gene              ens    Annotated as
0    SEPTIN7  ENSG00000122545  protein_coding
2     ABCB10  ENSG00000135776  protein_coding
4      ABCC6  ENSG00000091262  protein_coding
6    ABHD17A  ENSG00000129968  protein_coding
10    ACTR3B  ENSG00000133627  protein_coding
..       ...              ...             ...
565     SMN2  ENSG00000205571  protein_coding
566  SRGAP2B  ENSG00000196369  protein_coding
567  SRGAP2C  ENSG00000171943  protein_coding
568    TCAF1  ENSG00000198420  protein_coding
569    TCAF2  ENSG00000170379  protein_coding

[311 rows x 3 columns]

In [309]:
set(dup_genes_big)-set(hsg_dup.ens.tolist())
#those are all pseudogenes are readthorugh

{'ENSG00000244682', 'ENSG00000255104', 'ENSG00000267645', 'ENSG00000280204'}

In [311]:
#other sequence changes
hsg_seq=hsg_all[~(hsg_all.ens.isin(dup_genes_big))]
hsg_seq

           gene              ens    Annotated as
1         AATBC  ENSG00000215458       antisense
3        ABCC12  ENSG00000140798  protein_coding
5         ABCD4  ENSG00000119688  protein_coding
7      PKP4-AS1  ENSG00000204380       antisense
8    AC062028.1  ENSG00000145063          lncRNA
..          ...              ...             ...
536   LINC02073  ENSG00000267452          lncRNA
537   LINC00868  ENSG00000267535          lncRNA
538   LINC02712  ENSG00000273409          lncRNA
539   LINC02961  ENSG00000279261          lncRNA
540   LINC00602  ENSG00000281832          lncRNA

[259 rows x 3 columns]

In [313]:
#save those lists..
hsg_dup.to_csv("/scratch200/reutj/data/hsg_gene_lists/dup_genes_list")
hsg_seq.to_csv("/scratch200/reutj/data/hsg_gene_lists/seq_change_hsg_list")

In [ ]:
#check against paralog data

In [ ]:
#save to gmt files
def save_to_gmt(gene_list, gene_set_name, output_file):
    """
    Save a list of gene symbols to a .gmt file for GSEA.
    
    Parameters:
    - gene_list: List of gene symbols.
    - gene_set_name: Name of the gene set.
    - output_file: Path to the output .gmt file.
    """
    with open(output_file, 'w') as f:
        # .gmt format: GeneSetName, Description, Genes...
        line = [gene_set_name, "Custom gene set"] + gene_list
        f.write("\t".join(line) + "\n")